print ("D D D DD")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D       D")
print ("D D D DD")

